# ===============================================================================
# Ignytion IO - CRUCIBLE CORE
# Copyright (c) 2026 Ignytion IO. All rights reserved.
# Author      : IGNYTION_TECH
# File        : apb_synthesis_with_sky130pdk/01_rtl/Makefile
# Created     : 2026-09-08
# Description : Make entrypoint for the APB RTL source stage.
# ===============================================================================

.PHONY: all rtl list

all: rtl

rtl: list

list:
	@printf '%s\n' apb_protocol.v master.v slave1.v slave2.v
